# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in simple_banking.gemspec
gemspec

gem "csv", "~> 3.2", ">= 3.2.7"

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"
